# Generated by Django 5.2.17 on 2026-09-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unit_of_measurement", models.CharField(max_length=50)),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                ("cost_per_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_restocked", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "ingredients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Restock"),
                            ("USAGE", "Usage"),
                            ("SPOILAGE", "Spoilage"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.ingredient",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
